spring.application.name=api-gateway
server.port=8087

spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8080
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.server.webmvc.routes[1].id=course-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/subjects/**,/api/v1/courses/**,/api/v1/modules/**


spring.cloud.gateway.server.webmvc.routes[2].id=activity-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/activities/**

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/ai-learning-platform
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8090/realms/ai-learning-platform/protocol/openid-connect/certs

spring.security.oauth2.client.registration.api-gateway-service.client-id=api-gateway-service
spring.security.oauth2.client.registration.api-gateway-service.client-secret=${API_GATEWAY_SERVICE_SECRET}
spring.security.oauth2.client.registration.api-gateway-service.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.api-gateway-service.provider=keycloak
spring.security.oauth2.client.provider.keycloak.token-uri=http://localhost:8090/realms/ai-learning-platform/protocol/openid-connect/token